name: Get the last tag

on: 
    push:
        branches:
            - 'master'
    workflow_dispatch:
     
jobs:
  last-tag:
       
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
      - name: Get the last tag
        run: git describe --abbrev=0
